---
title: "Home Internet Access in the United States"
author: "P. M. Cooper"
date: "6/4/2020"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
---  
---    
## Internet Access  

- Many US households lack Internet access at home 
- Poses potential problem for school districts during pandemic 
- Related to poverty, urbanicity  
 
---  
---    

```{r , echo = FALSE, message=FALSE, warning=FALSE}
library(tidycensus)
library(plotly)

county18<-get_acs("county",survey = "acs1", key = "993d02931a941bd1f5af535c637800916aa504b2",variables=c("B28002_001","B28002_013","S1701_C03_002"))

cty18_wide<-data.frame(county18$GEOID[county18$variable=="B28002_001"],
                       county18$NAME[county18$variable=="B28002_001"],
                       county18$estimate[county18$variable=="B28002_001"],
                       county18$estimate[county18$variable=="B28002_013"],
                       county18$estimate[county18$variable=="S1701_C03_002"])

names(cty18_wide)<-c("GEOID","NAME","TOTPOP","NOINT","POVPCT")
cty18_wide<-cty18_wide[substr(cty18_wide$GEOID,1,2)!="72",]

cty18_wide$INTPCT<- with(cty18_wide,round((1-(NOINT/TOTPOP))*100,1))

fig<-plot_ly(x=cty18_wide$POVPCT,y=cty18_wide$INTPCT,
        alpha = 0.5)
fig<-layout(fig,title = "Counties in the US, 2018 American Community Survey",
                xaxis = list(title="Percent of Children in Poverty"),
                yaxis=list(title="Percent of Households with Home Internet")
                )
fig<-add_trace(fig,text=cty18_wide$NAME,hoverinfo = 'text',showlegend=T)
fig
```
---  

